// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.

/**
 * Represents permission scope values.
 */
/**
 * Values which set permission scope applicable to control plane related operations.
 */
export const SCOPE_ACCOUNT_READ = 0x0001;
export const SCOPE_ACCOUNT_LIST_DATABASES = 0x0002;
export const SCOPE_DATABASE_READ = 0x0004;
export const SCOPE_DATABASE_READ_OFFER = 0x0008;
export const SCOPE_DATABASE_LIST_CONTAINERS = 0x0010;
export const SCOPE_CONTAINER_READ = 0x0020;
export const SCOPE_CONTAINER_READ_OFFER = 0x0040;

export const SCOPE_ACCOUNT_CREATE_DATABASES = 0x0001;
export const SCOPE_ACCOUNT_DELETE_DATABASES = 0x0002;
export const SCOPE_DATABASE_DELETE = 0x0004;
export const SCOPE_DATABASE_REPLACE_OFFER = 0x0008;
export const SCOPE_DATABASE_CREATE_CONTAINERS = 0x0010;
export const SCOPE_DATABASE_DELETE_CONTAINERS = 0x0020;
export const SCOPE_CONTAINER_REPLACE = 0x0040;
export const SCOPE_CONTAINER_DELETE = 0x0080;
export const SCOPE_CONTAINER_REPLACE_OFFER = 0x0100;

export const SCOPE_ACCOUNT_READ_ALL_ACCESS = 0xffff;
export const SCOPE_DATABASE_READ_ALL_ACCESS =
  SCOPE_DATABASE_READ |
  SCOPE_DATABASE_READ_OFFER |
  SCOPE_DATABASE_LIST_CONTAINERS |
  SCOPE_CONTAINER_READ |
  SCOPE_CONTAINER_READ_OFFER;

export const SCOPE_CONTAINERS_READ_ALL_ACCESS = SCOPE_CONTAINER_READ | SCOPE_CONTAINER_READ_OFFER;

export const SCOPE_ACCOUNT_WRITE_ALL_ACCESS = 0xffff;
export const SCOPE_DATABASE_WRITE_ALL_ACCESS =
  SCOPE_DATABASE_DELETE |
  SCOPE_DATABASE_REPLACE_OFFER |
  SCOPE_DATABASE_CREATE_CONTAINERS |
  SCOPE_DATABASE_DELETE_CONTAINERS |
  SCOPE_CONTAINER_REPLACE |
  SCOPE_CONTAINER_DELETE |
  SCOPE_CONTAINER_REPLACE_OFFER;

export const SCOPE_CONTAINERS_WRITE_ALL_ACCESS =
  SCOPE_CONTAINER_REPLACE | SCOPE_CONTAINER_DELETE | SCOPE_CONTAINER_REPLACE_OFFER;

/**
 * Values which set permission scope applicable to data plane related operations.
 */
export const SCOPE_CONTAINER_EXECUTE_QUERIES = 0x00000001;
export const SCOPE_CONTAINER_READ_FEEDS = 0x00000002;
export const SCOPE_CONTAINER_READ_STORED_PROCEDURES = 0x00000004;
export const SCOPE_CONTAINER_READ_USER_DEFINED_FUNCTIONS = 0x00000008;
export const SCOPE_CONTAINER_READ_TRIGGERS = 0x00000010;
export const SCOPE_CONTAINER_READ_CONFLICTS = 0x00000020;
export const SCOPE_ITEM_READ = 0x00000040;
export const SCOPE_STORED_PROCEDURE_READ = 0x00000080;
export const SCOPE_USER_DEFINED_FUNCTION_READ = 0x00000100;
export const SCOPE_TRIGGER_READ = 0x00000200;

export const SCOPE_CONTAINER_CREATE_ITEMS = 0x00000001;
export const SCOPE_CONTAINER_REPLACE_ITEMS = 0x00000002;
export const SCOPE_CONTAINER_UPSERT_ITEMS = 0x00000004;
export const SCOPE_CONTAINER_DELETE_ITEMS = 0x00000008;
export const SCOPE_CONTAINER_CREATE_STORED_PROCEDURES = 0x00000010;
export const SCOPE_CONTAINER_REPLACE_STORED_PROCEDURES = 0x00000020;
export const SCOPE_CONTAINER_DELETE_STORED_PROCEDURES = 0x00000040;
export const SCOPE_CONTAINER_EXECUTE_STORED_PROCEDURES = 0x00000080;
export const SCOPE_CONTAINER_CREATE_TRIGGERS = 0x00000100;
export const SCOPE_CONTAINER_REPLACE_TRIGGERS = 0x00000200;
export const SCOPE_CONTAINER_DELETE_TRIGGERS = 0x00000400;
export const SCOPE_CONTAINER_CREATE_USER_DEFINED_FUNCTIONS = 0x00000800;
export const SCOPE_CONTAINER_REPLACE_USER_DEFINED_FUNCTIONS = 0x00001000;
export const SCOPE_CONTAINER_DELETE_USER_DEFINED_FUNCTIONS = 0x00002000;
export const SCOPE_CONTAINER_DELETE_CONFLICTS = 0x00004000;
export const SCOPE_ITEM_REPLACE = 0x00010000;
export const SCOPE_ITEM_UPSERT = 0x00020000;
export const SCOPE_ITEM_DELETE = 0x00040000;
export const SCOPE_STORED_PROCEDURE_REPLACE = 0x00100000;
export const SCOPE_STORED_PROCEDURE_DELETE = 0x00200000;
export const SCOPE_STORED_PROCEDURE_EXECUTE = 0x00400000;
export const SCOPE_USER_DEFINED_FUNCTION_REPLACE = 0x00800000;
export const SCOPE_USER_DEFINED_FUNCTION_DELETE = 0x01000000;
export const SCOPE_TRIGGER_REPLACE = 0x02000000;
export const SCOPE_TRIGGER_DELETE = 0x04000000;
export const SCOPE_CONTAINER_READ_ALL_ACCESS = 0xffffffff;
export const SCOPE_ITEM_READ_ALL_ACCESS = SCOPE_CONTAINER_EXECUTE_QUERIES | SCOPE_ITEM_READ;
export const SCOPE_CONTAINER_WRITE_ALL_ACCESS = 0xffffffff;
export const SCOPE_ITEM_WRITE_ALL_ACCESS =
  SCOPE_CONTAINER_CREATE_ITEMS |
  SCOPE_CONTAINER_REPLACE_ITEMS |
  SCOPE_CONTAINER_UPSERT_ITEMS |
  SCOPE_CONTAINER_DELETE_ITEMS |
  SCOPE_ITEM_REPLACE |
  SCOPE_ITEM_UPSERT |
  SCOPE_ITEM_DELETE;

export const NONE = 0;
