// Copyright (c) Microsoft Corporation.
// Licensed under the MIT license

export enum SasTokenPermissionKind {

  CONTAINER_CREATE_ITEMS,

  CONTAINER_REPLACE_ITEMS,

  CONTAINER_UPSERT_ITEMS,

  CONTAINER_DELETE_ITEMS,

  CONTAINER_EXECUTE_QUERIES,

  CONTAINER_READ_FEEDS,

  CONTAINER_CREATE_STORE_PROCEDURES,

  CONTAINER_READ_STORE_PROCEDURES,

  CONTAINER_REPLACE_STORE_PROCEDURES,

  CONTAINER_DELETE_STORE_PROCEDURES,

  CONTAINER_CREATE_TRIGGERS,

  CONTAINER_READ_TRIGGERS,

  CONTAINER_REPLACE_TRIGGERS,

  CONTAINER_DELETE_TRIGGERS,

  CONTAINER_CREATE_USER_DEFINED_FUNCTIONS,

  CONTAINER_READ_USER_DEFINED_FUNCTIONS,

  CONTAINER_REPLACE_USER_DEFINED_FUNCTIONS,

  CONTAINER_DELETE_USER_DEFINED_FUNCTIONS,

  CONTAINER_EXECUTE_STORED_PROCEDURES,

  CONTAINER_READ_CONFLICTS,

  CONTAINER_DELETE_CONFLICTS,

  CONTAINER_READ_ANY,

  CONTAINER_FULL_ACCESS,

  ITEM_READ_ANY,

  ITEM_FULL_ACCESS,

  ITEM_READ,

  ITEM_REPLACE,

  ITEM_UPSERT,

  ITEM_DELETE,

  STORE_PROCEDURE_READ,

  STORE_PROCEDURE_REPLACE,

  STORE_PROCEDURE_DELETE,

  STORE_PROCEDURE_EXECUTE,

  USER_DEFINED_FUNCTION_READ,

  USER_DEFINED_FUNCTION_REPLACE,

  USER_DEFINED_FUNCTION_DELETE,

  TRIGGER_READ,

  TRIGGER_REPLACE,

  TRIGGER_DELETE,
}
